# Generated by Django 4.2 on 2023-04-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='routeLogistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleNumber', models.CharField(max_length=200, null=True, unique=True)),
                ('route', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('out of depot', 'out of depot'), ('on th route', 'on th route'), ('out of service', 'out of service'), ('on destination', 'on destination')], max_length=200)),
                ('destination', models.CharField(max_length=200, null=True)),
                ('team', models.CharField(choices=[('TeamA', 'TeamA'), ('TeamB', 'TeamB'), ('TeamC', 'TeamC'), ('TeamD', 'TeamD')], max_length=200, null=True)),
            ],
        ),
    ]
